name: ISHAQ-MD 
services:
  - name: 𝑰𝑺𝑯𝑨𝑸-𝐌𝐃-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
